#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 24 14:49:39 2018

@author: suliat16

Test file for cons
"""
import unittest
import cons

class TestCons(unittest.TestCase):
    """
    """
    def setUp(self):
        strlyz = ("MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANWMCLAKWESGY"
                  "NTRATNYNAGDRSTDYGIFQINSRYWCNDGKTPGAVNACHLSCSALLQDNIADAVAC"
                  "AKRVVRDPQGIRAWVAWRNRCQNRDVRQYVQGCGV")
        lyz = cons.OrthologFinder(strlyz)
        stragg = ('YYYYYYYYYYYVVVVVVVVVVVVBBBBBBBBBBBAAAAAAAAAAANNNNNNNNNNN'
                  'MMMMMMMMMMMWWWWWWWWWWWWWCCCCCCCCCCSSSSSSSSSS')
        aggregate = cons.OrthologFinder(stragg)
        arabidopsisCDC48A = ("MSTPAESSDSKSKKDFSTAILERKKSPNRLVVDEAINDDNSVVSLHPAT"
                              "MEKLQLFRGDTILIKGKKRKDTVCIALADETCEEPKIRMNKVVRSNLRVR"
                              "LGDVISVHQCPDVKYGKRVHILPVDDTVEGVTGNLFDAYLKPYFLEAYRP"
                              "VRKGDLFLVRGGMRSVEFKVIETDPAEYCVVAPDTEIFCEGEPVKREDEE"
                              "RLDDVGYDDVGGVRKQMAQIRELVELPLRHPQLFKSIGVKPPKGILLYGP"
                              "PGSGKTLIARAVANETGAFFFCINGPEIMSKLAGESESNLRKAFEEAEKN"
                              "APSIIFIDEIDSIAPKREKTNGEVERRIVSQLLTLMDGLKSRAHVIVMGA"
                              "TNRPNSIDPALRRFGRFDREIDIGVPDEIGRLEVLRIHTKNMKLAEDVDLE"
                              "RISKDTHGYVGADLAALCTEAALQCIREKMDVIDLEDDSIDAEILNSMAVTN"
                              "EHFHTALGNSNPSALRETVVEVPNVSWNDIGGLENVKRELQETVQYPVEHP"
                              "EKFEKFGMSPSKGVLFYGPPGCGKTLLAKAIANECQANFISVKGPELLTMWF"
                              "GESEANVREIFDKARQSAPCVLFFDELDSIATQRGGGSGGDGGGAADRVL"
                              "NQLLTEMDGMNAKKTVFIIGATNRPDIIDSALLRPGRLDQLIYIPLPDED"
                              "SRLNIFKAALRKSPIAKDVDIGALAKYTQGFSGADITEICQRACKYAIR"
                              "ENIEKDIEKEKRRSENPEAMEEDGVDEVSEIKAAHFEESMKYARRSVSDA"
                              "DIRKYQAFAQTLQQSRGFGSEFRFENSAGSGATTGVADPFATSAAAAGDDD"
                              "DLYN")
        CDC48A = cons.OrthologFinder(arabidopsisCDC48A)

        humanPYK2 = ("MSGVSEPLSRVKLGTLRRPEGPAEPMVVVPVDVEKEDVRILKVCFYSNSFNPGKNF"
                      "KLVKCTVQTEIREIITSILLSGRIGPNIRLAECYGLRLKHMKSDEIHWLHPQMTVGE"
                      "VQDKYECLHVEAEWRYDLQIRYLPEDFMESLKEDRTTLLYFYQQLRNDYMQRYASKV"
                      "SEGMALQLGCLELRRFFKDMPHNALDKKSNFELLEKEVGLDLFFPKQMQENLKPKQF"
                      "RKMIQQTFQQYASLREEECVMKFFNTLAGFANIDQETYRCELIQGWNITVDLVIGPK"
                      "GIRQLTSQDAKPTCLAEFKQIRSIRCLPLEEGQAVLQLGIEGAPQALSIKTSSLAEA"
                      "ENMADLIDGYCRLQGEHQGSLIIHPRKDGEKRNSLPQIPMLNLEARRSHLSESCSIE"
                      "SDIYAEIPDETLRRPGGPQYGIAREDVVLNRILGEGFFGEVYEGVYTNHKGEKINVAV"
                      "KTCKKDCTLDNKEKFMSEAVIMKNLDHPHIVKLIGIIEEEPTWIIMELYPYGELGHY"
                      "LERNKNSLKVLTLVLYSLQICKAMAYLESINCVHRDIAVRNILVASPECVKLGDFGL"
                      "SRYIEDEDYYKASVTRLPIKWMSPESINFRRFTTASDVWMFAVCMWEILSFGKQPFF"
                      "WLENKDVIGVLEKGDRLPKPDLCPPVLYTLMTRCWDYDPSDRPRFTELVCSLSDVYQM"
                      "EKDIAMEQERNARYRTPKILEPTAFQEPPPKPSRPKYRPPPQTNLLAPKLQFQVPEG"
                      "LCASSPTLTSPMEYPSPVNSLHTPPLHRHNVFKRHSMREEDFIQPSSREEAQQLWEA"
                      "EKVKMRQILDKQQKQMVEDYQWLRQEEKSLDPMVYMNDKSPLTPEKEVGYLEFTGPP"
                      "QKPPRLGAQSIQPTANLDRTDDLVYLNVMELVRAVLELKNELCQLPPEGYVVVVKNV"
                      "GLTLRKLIGSVDDLLPSLPSSSRTEIEGTQKLLNKDLAELINKMRLAQQNAVTSLSE"
                      "ECKRQMLTASHTLAVDAKNLLDAVDQAKVLANLAHPPAE")
        PYK2 = cons.OrthologFinder(humanPYK2)

    def test_retOMA_lyz(self):
        pass
        